"""Add storage_status

Revision ID: 309f236ec95f
Revises: a65ae0c8bf75
Create Date: 2026-09-28 17:50:43.621800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309f236ec95f'
down_revision: Union[str, None] = 'a65ae0c8bf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    storage_status = sa.Enum('PENDING_UPLOAD', 'AVAILABLE', 'FAILED_RETRYABLE', 'FAILED_PERMANENT', name='storagestatus')
    storage_status.create(op.get_bind(), checkfirst=True)
    
    op.add_column('human_reviews', sa.Column('storage_status', storage_status, nullable=False, server_default='PENDING_UPLOAD'))
    op.add_column('human_reviews', sa.Column('local_storage_path', sa.String(), nullable=True))
    op.alter_column('human_reviews', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('human_reviews', 'audit_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_human_reviews_org_id', table_name='human_reviews')
    op.drop_index('ix_human_reviews_reviewer_id', table_name='human_reviews')
    op.create_index(op.f('ix_human_reviews_organization_id'), 'human_reviews', ['organization_id'], unique=False)
    op.add_column('ml_training_samples', sa.Column('storage_status', storage_status, nullable=False, server_default='PENDING_UPLOAD'))
    op.add_column('ml_training_samples', sa.Column('local_storage_path', sa.String(), nullable=True))
    op.add_column('ml_training_samples', sa.Column('upload_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ml_training_samples', sa.Column('last_upload_error', sa.String(), nullable=True))
    op.alter_column('ml_training_samples', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_ml_samples_org_id', table_name='ml_training_samples')
    op.create_index(op.f('ix_ml_training_samples_organization_id'), 'ml_training_samples', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_samples_organization_id'), table_name='ml_training_samples')
    op.create_index('ix_ml_samples_org_id', 'ml_training_samples', ['organization_id'], unique=False)
    op.alter_column('ml_training_samples', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('ml_training_samples', 'last_upload_error')
    op.drop_column('ml_training_samples', 'upload_attempts')
    op.drop_column('ml_training_samples', 'local_storage_path')
    op.drop_column('ml_training_samples', 'storage_status')
    op.drop_index(op.f('ix_human_reviews_organization_id'), table_name='human_reviews')
    op.create_index('ix_human_reviews_reviewer_id', 'human_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_human_reviews_org_id', 'human_reviews', ['organization_id'], unique=False)
    op.alter_column('human_reviews', 'audit_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('human_reviews', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('human_reviews', 'local_storage_path')
    op.drop_column('human_reviews', 'storage_status')
    # ### end Alembic commands ###
