"""Init Schema Phase 8

Revision ID: ece8da61aba3
Revises: 
Create Date: 2026-09-22 17:56:57.781081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece8da61aba3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='orgstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('artifact_storage_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('TRAINING', 'CANDIDATE', 'VALIDATED', 'APPROVED', 'ACTIVE', 'RETIRED', name='modelstatus'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'model_name', 'version', name='uq_model_version')
    )
    op.create_index(op.f('ix_model_versions_organization_id'), 'model_versions', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'barcode', name='uq_organization_barcode'),
    sa.UniqueConstraint('organization_id', 'sku_code', name='uq_organization_sku')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='storestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_organization_store_code')
    )
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('planograms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='planogramstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_organization_planogram_code')
    )
    op.create_index(op.f('ix_planograms_code'), 'planograms', ['code'], unique=False)
    op.create_index(op.f('ix_planograms_organization_id'), 'planograms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_planograms_store_id'), 'planograms', ['store_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('store_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'store_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('planogram_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planogram_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'RETIRED', name='planogramversionstatus'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planogram_id'], ['planograms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planogram_id', 'version_number', name='uq_planogram_version')
    )
    op.create_index(op.f('ix_planogram_versions_planogram_id'), 'planogram_versions', ['planogram_id'], unique=False)
    op.create_table('planogram_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planogram_version_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planogram_version_id'], ['planogram_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planogram_version_id', 'shelf_id', 'position', name='uq_planogram_version_shelf_pos')
    )
    op.create_index(op.f('ix_planogram_positions_planogram_version_id'), 'planogram_positions', ['planogram_version_id'], unique=False)
    op.create_index(op.f('ix_planogram_positions_product_id'), 'planogram_positions', ['product_id'], unique=False)
    op.create_table('shelf_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('planogram_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='auditstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planogram_version_id'], ['planogram_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_audits_employee_id'), 'shelf_audits', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shelf_audits_organization_id'), 'shelf_audits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shelf_audits_planogram_version_id'), 'shelf_audits', ['planogram_version_id'], unique=False)
    op.create_index(op.f('ix_shelf_audits_status'), 'shelf_audits', ['status'], unique=False)
    op.create_index(op.f('ix_shelf_audits_store_id'), 'shelf_audits', ['store_id'], unique=False)
    op.create_table('audit_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_images_audit_id'), 'audit_images', ['audit_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('position_accuracy', sa.Float(), nullable=False),
    sa.Column('availability_rate', sa.Float(), nullable=False),
    sa.Column('facing_compliance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_audit_id'), 'compliance_results', ['audit_id'], unique=True)
    op.create_table('compliance_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('expected_product_id', sa.UUID(), nullable=True),
    sa.Column('actual_product_id', sa.UUID(), nullable=True),
    sa.Column('violation_type', sa.Enum('MISSING_PRODUCT', 'EXTRA_PRODUCT', 'MISPLACED_PRODUCT', 'FACING_MISMATCH', name='violationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actual_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expected_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_violations_audit_id'), 'compliance_violations', ['audit_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('ML_PIPELINE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_audit_id'), 'processing_jobs', ['audit_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('crop_storage_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['audit_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_audit_id'), 'detections', ['audit_id'], unique=False)
    op.create_index(op.f('ix_detections_image_id'), 'detections', ['image_id'], unique=False)
    op.create_table('recognitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('predicted_product_id', sa.UUID(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['predicted_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognitions_detection_id'), 'recognitions', ['detection_id'], unique=True)
    op.create_table('actual_shelf_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=True),
    sa.Column('recognition_id', sa.UUID(), nullable=True),
    sa.Column('center_x', sa.Float(), nullable=True),
    sa.Column('center_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['shelf_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_shelf_positions_audit_id'), 'actual_shelf_positions', ['audit_id'], unique=False)
    op.create_index(op.f('ix_actual_shelf_positions_product_id'), 'actual_shelf_positions', ['product_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recognition_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('predicted_product_id', sa.UUID(), nullable=True),
    sa.Column('correct_product_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['correct_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['predicted_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_recognition_id'), 'human_reviews', ['recognition_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewer_id'), 'human_reviews', ['reviewer_id'], unique=False)
    op.create_table('ml_training_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_storage_key', sa.String(), nullable=False),
    sa.Column('correct_product_id', sa.UUID(), nullable=False),
    sa.Column('human_review_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INCLUDED_IN_DATASET', 'REJECTED', name='samplestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['correct_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['human_review_id'], ['human_reviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_training_samples')
    op.drop_index(op.f('ix_human_reviews_reviewer_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_recognition_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_actual_shelf_positions_product_id'), table_name='actual_shelf_positions')
    op.drop_index(op.f('ix_actual_shelf_positions_audit_id'), table_name='actual_shelf_positions')
    op.drop_table('actual_shelf_positions')
    op.drop_index(op.f('ix_recognitions_detection_id'), table_name='recognitions')
    op.drop_table('recognitions')
    op.drop_index(op.f('ix_detections_image_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_audit_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_processing_jobs_audit_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_compliance_violations_audit_id'), table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index(op.f('ix_compliance_results_audit_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_audit_images_audit_id'), table_name='audit_images')
    op.drop_table('audit_images')
    op.drop_index(op.f('ix_shelf_audits_store_id'), table_name='shelf_audits')
    op.drop_index(op.f('ix_shelf_audits_status'), table_name='shelf_audits')
    op.drop_index(op.f('ix_shelf_audits_planogram_version_id'), table_name='shelf_audits')
    op.drop_index(op.f('ix_shelf_audits_organization_id'), table_name='shelf_audits')
    op.drop_index(op.f('ix_shelf_audits_employee_id'), table_name='shelf_audits')
    op.drop_table('shelf_audits')
    op.drop_index(op.f('ix_planogram_positions_product_id'), table_name='planogram_positions')
    op.drop_index(op.f('ix_planogram_positions_planogram_version_id'), table_name='planogram_positions')
    op.drop_table('planogram_positions')
    op.drop_index(op.f('ix_planogram_versions_planogram_id'), table_name='planogram_versions')
    op.drop_table('planogram_versions')
    op.drop_table('user_roles')
    op.drop_table('store_users')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_planograms_store_id'), table_name='planograms')
    op.drop_index(op.f('ix_planograms_organization_id'), table_name='planograms')
    op.drop_index(op.f('ix_planograms_code'), table_name='planograms')
    op.drop_table('planograms')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_organization_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_model_versions_organization_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
